### ISSUE TITLE
Working service

### ISSUE THREAD

**Issue by luisve1427** [kedacore/sample-dotnet-worker-servicebus-queue#43]
How does KEDA knows that the service has completed the work related to the event and that the instance / pod can be killed? The scenario I have is that I received the last event on the queue, there is a long process to be executed based on the event, I want to scale to 0 but ensure the work is completed before that happens.

**Comment by tomkerkhove** [comment]
KEDA doesn't know :)

That's why KEDA supports `ScaledObject` & `ScaledJob`:
- `ScaledObject` scales deamon-like workloads and doesn't take that in to consideration - It's up to the app to gracefully shut down
- `ScaledJob` scales by using Jobs in Kubernetes to spin up an instance per event and let it run to completion.

What you need, I believe, is a `ScaledJob`.

**Comment by luisve1427** [comment]
thanks
